"""Change name for rating column

Revision ID: ebe813b2a44d
Revises: f0366bd800cc
Create Date: 2026-02-11 13:54:10.523688

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "ebe813b2a44d"
down_revision: Union[str, Sequence[str], None] = "f0366bd800cc"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "products",
        sa.Column("rating", sa.Numeric(), server_default=sa.text("0"), nullable=False),
    )
    op.drop_column("products", "rate")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "products",
        sa.Column(
            "rate",
            sa.NUMERIC(),
            server_default=sa.text("0"),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.drop_column("products", "rating")
    # ### end Alembic commands ###
