"""Add avg rating for Product model

Revision ID: f0366bd800cc
Revises: 24ee2ecada1c
Create Date: 2026-02-11 13:46:17.972494

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "f0366bd800cc"
down_revision: Union[str, Sequence[str], None] = "24ee2ecada1c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "products",
        sa.Column("rate", sa.Numeric(), server_default=sa.text("0"), nullable=False),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("products", "rate")
    # ### end Alembic commands ###
